import typescript from 'rollup-plugin-typescript2'
import pkg from './package.json'
export default {
  input: 'src/index.ts',
  output: [
    {
      dir: 'dist',
      format: 'cjs',
      // sourcemap: true,
    },
    {
      dir: 'dist/es',
      format: 'es',
      // sourcemap: true,
    },
  ],
  external: [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.peerDependencies || {}),
    'events',
    'lodash/capitalize',
    'lodash/cloneDeep',
    'lodash/get',
    'lodash/has',
    'lodash/isArray',
    'lodash/isDate',
    'lodash/isBoolean',
    'lodash/isEmpty',
    'lodash/isFunction',
    'lodash/isInteger',
    'lodash/isNull',
    'lodash/isNumber',
    'lodash/isObject',
    'lodash/isPlainObject',
    'lodash/isRegExp',
    'lodash/isString',
    'lodash/isUndefined',
    'lodash/merge',
    'lodash/set',
    'lodash/toInteger',
    'lodash/toNumber',
    'lodash/trimEnd',
    'lodash/uniq',
    'lodash/debounce',
    'lodash/throttle',
    '@material-ui/core/Chip',
    '@material-ui/core/styles/colorManipulator',
    '@material-ui/core/Card',
    '@material-ui/core/CardHeader',
    '@material-ui/core/CardContent',
    '@material-ui/core/ExpansionPanel',
    '@material-ui/core/ExpansionPanelSummary',
    '@material-ui/core/ExpansionPanelDetails',
    '@material-ui/core/AppBar',
    '@material-ui/core/Tabs',
    '@material-ui/core/Tab',
    '@material-ui/core/Paper',
    '@material-ui/core/MenuItem',
    '@material-ui/core/Checkbox',
    '@material-ui/core/Radio',
    '@material-ui/core/RadioGroup',
    '@material-ui/core/FormControlLabel',
    '@material-ui/core/Switch',
    '@material-ui/core/FormGroup',
    '@material-ui/core/Button',
    '@material-ui/core/IconButton',
    '@material-ui/core/SvgIcon',
    '@material-ui/core/Divider',
    '@material-ui/core/CardMedia',
    '@material-ui/core/Typography',
    '@material-ui/core/Table',
    '@material-ui/core/TableBody',
    '@material-ui/core/TableCell',
    '@material-ui/core/TableHead',
    '@material-ui/core/TablePagination',
    '@material-ui/core/TableRow',
    '@material-ui/core/TableSortLabel',
    '@material-ui/core/Toolbar',
    '@material-ui/core/TextField',
    '@material-ui/core/InputAdornment',
    '@material-ui/core/FormControl',
    '@material-ui/core/FormHelperText',
    '@material-ui/core/FormLabel',
    '@material-ui/core/Icon',
    '@material-ui/core/Tooltip',
    '@material-ui/core/Grid',
    '@material-ui/core/styles',
    '@material-ui/core/CssBaseline',
    '@material-ui/core/Drawer',
    '@material-ui/core/Dialog',
    '@material-ui/core/DialogActions',
    '@material-ui/core/DialogContent',
    '@material-ui/core/DialogContentText',
    '@material-ui/core/DialogTitle',
  ],
  plugins: [
    typescript({
      useTsconfigDeclarationDir: true
    }),
  ],
}