export const countries = [
  'Albania',
  'Argentina',
  'Armenia',
  'Austria',
  'Bahamas',
  'Bahrain',
  'Cambodia',
  'Cameroon',
  'Canada',
  'China',
  'Costa Rica',
  // 'Croatia',
  // 'Cuba',
  // 'Dominica',
  // 'Dominican Republic',
  // 'Ecuador',
  // 'Egypt',
  // 'Finland',
  // 'France',
  // 'Gabon',
  // 'Gambia',
  // 'Germany',
  // 'Greece',
  // 'Grenada',
  // 'Haiti',
  // 'Hungary',
  // 'Iceland',
  // 'India',
  // 'Indonesia',
  // 'Jamaica',
  // 'Japan',
  // 'Kenya',
  // 'Kiribati',
  // 'Korea North',
  // 'Korea South',
  // 'Laos',
  // 'Latvia',
  // 'Liechtenstein',
  // 'Luxembourg',
  // 'Macedonia',
  // 'Madagascar',
  // 'Monaco',
  // 'Morocco',
  // 'Nauru',
  // 'Nepal',
  // 'Netherlands',
  // 'Norway',
  // 'Oman',
  // 'Palau',
  // 'Panama',
  // 'Portugal',
  // 'Qatar',
  // 'Romania',
  // 'St Kitts & Nevis',
  // 'St Lucia',
  // 'Samoa',
  // 'San Marino',
  // 'Somalia',
  // 'South Africa',
  // 'Swaziland',
  // 'Switzerland',
  // 'Tajikistan',
  // 'Togo',
  // 'Tonga',
  // 'Trinidad & Tobago',
  // 'Uganda',
  // 'Ukraine',
  // 'United Arab Emirates',
  // 'United States',
  // 'Vanuatu',
  // 'Vatican City',
  // 'Vietnam',
  // 'Yemen',
  // 'Zambia',
  // 'Zimbabwe'
]

export const animals =
[
  'albatross',
  'alligator',
  'ant',
  'antelope',
  'ape',
  'armadillo',
  // "barracuda",
  // "bat",
  // "bear",
  // "bison",
  // "buffalo",
  // "butterfly",
  // "camel",
  // "cat",
  // "caterpillar",
  // "chimpanzee",
  // "cobra",
  // "cod",
  // "cormorant",
  // "coyote",
  // "crocodile",
  // "crow",
  // "deer",
  // "dinosaur",
  // "dog",
  // "donkey",
  // "eagle",
  // "elephant",
  // "fish",
  // "fly",
  // "fox",
  // "frog",
  // "gazelle",
  // "giraffe",
  // "goldfish",
  // "gorilla",
  // "grasshopper",
  // "hamster",
  // "hawk",
  // "hippopotamus",
  // "ibex",
  // "ibis",
  // "jellyfish",
  // "kangaroo",
  // "lapwing",
  // "lyrebird",
  // "magpie",
  // "mosquito",
  // "nightingale",
  // "okapi",
  // "panther",
  // "pheasant",
  // "pig",
  // "quail",
  // "rabbit",
  // "rail",
  // "ram",
  // "rat",
  // "red-deer",
  // "salmon",
  // "sand-dollar",
  // "sea-lion",
  // "sea-urchin",
  // "shark",
  // "sheep",
  // "tarsier",
  // "termite",
  // "tiger",
  // "wasp",
  // "weasel",
  // "whale",
  // "wolf",
  // "wolverine",
  // "worm",
  // "yak",
  // "zebra"
  ]
